-- Table pour stocker la configuration de l'événement
CREATE TABLE IF NOT EXISTS event_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_title TEXT NOT NULL DEFAULT 'Party Wall',
  event_subtitle TEXT NOT NULL DEFAULT 'Live',
  scroll_speed TEXT NOT NULL DEFAULT 'normal', -- 'slow', 'normal', 'fast'
  slide_transition TEXT NOT NULL DEFAULT 'fade', -- 'fade', 'slide', 'zoom'
  decorative_frame_enabled BOOLEAN NOT NULL DEFAULT false,
  decorative_frame_url TEXT,
  caption_generation_enabled BOOLEAN NOT NULL DEFAULT true,
  content_moderation_enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Si la table existait déjà, ajouter les colonnes manquantes
ALTER TABLE event_settings
  ADD COLUMN IF NOT EXISTS decorative_frame_enabled BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE event_settings
  ADD COLUMN IF NOT EXISTS decorative_frame_url TEXT;

ALTER TABLE event_settings
  ADD COLUMN IF NOT EXISTS caption_generation_enabled BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE event_settings
  ADD COLUMN IF NOT EXISTS content_moderation_enabled BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE event_settings
  ADD COLUMN IF NOT EXISTS auto_battles_enabled BOOLEAN NOT NULL DEFAULT false;

-- Assurer qu'il y a au moins une ligne (ID 1)
INSERT INTO event_settings (id, event_title, event_subtitle, scroll_speed, slide_transition, decorative_frame_enabled, decorative_frame_url, caption_generation_enabled, content_moderation_enabled)
SELECT 1, 'Party Wall', 'Live', 'normal', 'fade', false, null, true, true
WHERE NOT EXISTS (SELECT 1 FROM event_settings);

-- Activer RLS
ALTER TABLE event_settings ENABLE ROW LEVEL SECURITY;

-- Supprimer les anciennes politiques pour éviter les conflits si on ré-exécute
DROP POLICY IF EXISTS "Public settings access" ON event_settings;
DROP POLICY IF EXISTS "Admin update settings" ON event_settings;
DROP POLICY IF EXISTS "Admin insert settings" ON event_settings;

-- Politique de lecture : Tout le monde peut lire la configuration
CREATE POLICY "Public settings access" ON event_settings
  FOR SELECT USING (true);

-- Politique d'écriture (UPDATE) : Seuls les utilisateurs authentifiés
CREATE POLICY "Admin update settings" ON event_settings
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Politique d'écriture (INSERT) : Seuls les utilisateurs authentifiés
-- Nécessaire pour upsert si la ligne n'existait pas (bien que l'INSERT ci-dessus devrait l'avoir créée)
CREATE POLICY "Admin insert settings" ON event_settings
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');
