/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallRouteImport } from './routes/wall'
import { Route as StatsDisplayRouteImport } from './routes/stats-display'
import { Route as ProjectionRouteImport } from './routes/projection'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MobileControlRouteImport } from './routes/mobile-control'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FindmeRouteImport } from './routes/findme'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DataManagementRouteImport } from './routes/data-management'
import { Route as CollageRouteImport } from './routes/collage'
import { Route as BattleResultsRouteImport } from './routes/battle-results'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsDisplayRoute = StatsDisplayRouteImport.update({
  id: '/stats-display',
  path: '/stats-display',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionRoute = ProjectionRouteImport.update({
  id: '/projection',
  path: '/projection',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileControlRoute = MobileControlRouteImport.update({
  id: '/mobile-control',
  path: '/mobile-control',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FindmeRoute = FindmeRouteImport.update({
  id: '/findme',
  path: '/findme',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DataManagementRoute = DataManagementRouteImport.update({
  id: '/data-management',
  path: '/data-management',
  getParentRoute: () => rootRouteImport,
} as any)
const CollageRoute = CollageRouteImport.update({
  id: '/collage',
  path: '/collage',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleResultsRoute = BattleResultsRouteImport.update({
  id: '/battle-results',
  path: '/battle-results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/battle-results': typeof BattleResultsRoute
  '/collage': typeof CollageRoute
  '/data-management': typeof DataManagementRoute
  '/events': typeof EventsRoute
  '/findme': typeof FindmeRoute
  '/gallery': typeof GalleryRoute
  '/guest': typeof GuestRoute
  '/help': typeof HelpRoute
  '/mobile-control': typeof MobileControlRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/projection': typeof ProjectionRoute
  '/stats-display': typeof StatsDisplayRoute
  '/wall': typeof WallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/battle-results': typeof BattleResultsRoute
  '/collage': typeof CollageRoute
  '/data-management': typeof DataManagementRoute
  '/events': typeof EventsRoute
  '/findme': typeof FindmeRoute
  '/gallery': typeof GalleryRoute
  '/guest': typeof GuestRoute
  '/help': typeof HelpRoute
  '/mobile-control': typeof MobileControlRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/projection': typeof ProjectionRoute
  '/stats-display': typeof StatsDisplayRoute
  '/wall': typeof WallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/battle-results': typeof BattleResultsRoute
  '/collage': typeof CollageRoute
  '/data-management': typeof DataManagementRoute
  '/events': typeof EventsRoute
  '/findme': typeof FindmeRoute
  '/gallery': typeof GalleryRoute
  '/guest': typeof GuestRoute
  '/help': typeof HelpRoute
  '/mobile-control': typeof MobileControlRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/projection': typeof ProjectionRoute
  '/stats-display': typeof StatsDisplayRoute
  '/wall': typeof WallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/battle-results'
    | '/collage'
    | '/data-management'
    | '/events'
    | '/findme'
    | '/gallery'
    | '/guest'
    | '/help'
    | '/mobile-control'
    | '/onboarding'
    | '/privacy'
    | '/projection'
    | '/stats-display'
    | '/wall'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/battle-results'
    | '/collage'
    | '/data-management'
    | '/events'
    | '/findme'
    | '/gallery'
    | '/guest'
    | '/help'
    | '/mobile-control'
    | '/onboarding'
    | '/privacy'
    | '/projection'
    | '/stats-display'
    | '/wall'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/battle-results'
    | '/collage'
    | '/data-management'
    | '/events'
    | '/findme'
    | '/gallery'
    | '/guest'
    | '/help'
    | '/mobile-control'
    | '/onboarding'
    | '/privacy'
    | '/projection'
    | '/stats-display'
    | '/wall'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BattleResultsRoute: typeof BattleResultsRoute
  CollageRoute: typeof CollageRoute
  DataManagementRoute: typeof DataManagementRoute
  EventsRoute: typeof EventsRoute
  FindmeRoute: typeof FindmeRoute
  GalleryRoute: typeof GalleryRoute
  GuestRoute: typeof GuestRoute
  HelpRoute: typeof HelpRoute
  MobileControlRoute: typeof MobileControlRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectionRoute: typeof ProjectionRoute
  StatsDisplayRoute: typeof StatsDisplayRoute
  WallRoute: typeof WallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats-display': {
      id: '/stats-display'
      path: '/stats-display'
      fullPath: '/stats-display'
      preLoaderRoute: typeof StatsDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projection': {
      id: '/projection'
      path: '/projection'
      fullPath: '/projection'
      preLoaderRoute: typeof ProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-control': {
      id: '/mobile-control'
      path: '/mobile-control'
      fullPath: '/mobile-control'
      preLoaderRoute: typeof MobileControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findme': {
      id: '/findme'
      path: '/findme'
      fullPath: '/findme'
      preLoaderRoute: typeof FindmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-management': {
      id: '/data-management'
      path: '/data-management'
      fullPath: '/data-management'
      preLoaderRoute: typeof DataManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collage': {
      id: '/collage'
      path: '/collage'
      fullPath: '/collage'
      preLoaderRoute: typeof CollageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-results': {
      id: '/battle-results'
      path: '/battle-results'
      fullPath: '/battle-results'
      preLoaderRoute: typeof BattleResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BattleResultsRoute: BattleResultsRoute,
  CollageRoute: CollageRoute,
  DataManagementRoute: DataManagementRoute,
  EventsRoute: EventsRoute,
  FindmeRoute: FindmeRoute,
  GalleryRoute: GalleryRoute,
  GuestRoute: GuestRoute,
  HelpRoute: HelpRoute,
  MobileControlRoute: MobileControlRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectionRoute: ProjectionRoute,
  StatsDisplayRoute: StatsDisplayRoute,
  WallRoute: WallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
