/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingRoute } from './routes/onboarding'
import { Route as IndexRoute } from './routes/index'
import { Route as HelpRoute } from './routes/help'
import { Route as EventsRoute } from './routes/events'
import { Route as DataManagementRoute } from './routes/data-management'
import { Route as PrivacyRoute } from './routes/privacy'

// Create/Update Routes

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren()
const IndexRouteWithChildren = IndexRoute._addFileChildren()
const HelpRouteWithChildren = HelpRoute._addFileChildren()
const EventsRouteWithChildren = EventsRoute._addFileChildren()
const DataManagementRouteWithChildren = DataManagementRoute._addFileChildren()
const PrivacyRouteWithChildren = PrivacyRoute._addFileChildren()

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/data-management': {
      id: '/data-management'
      path: '/data-management'
      fullPath: '/data-management'
      preLoaderRoute: typeof DataManagementRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteWithChildren
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteWithChildren,
  DataManagementRouteWithChildren,
  EventsRouteWithChildren,
  HelpRouteWithChildren,
  OnboardingRouteWithChildren,
  PrivacyRouteWithChildren,
})

/* prettier-ignore-end */

